### ISSUE TITLE
Remove schedule from README.md

### ISSUE THREAD

**Issue by yungyuc** [YJack0000/SimEvo#1]
When uploading to PyPI `README.md` is included in the package description, and it looks abrupt to have a section of schedule in it:

<img width="836" alt="image" src="https://github.com/YJack0000/SimEvo/assets/399122/28bfa6fa-0407-4794-a5ac-f4a1b7795c76">

I suggest to remove the section of schedule from `README.md`.  If you like to keep the schedule, an issue is a good place for it.

**Comment by YJack0000** [comment]
Thank you for the suggestion! I agree that the schedule section might be better suited for an issue discussion.

Also, I am planning to automate tagging commits with PR or issue numbers upon merges. This should help us track changes more effectively!

**Comment by yungyuc** [comment]
> Also, I am planning to automate tagging commits with PR or issue numbers upon merges. This should help us track changes more effectively!

I am not sure an automation like that is productive at the moment.  Do you already have a collaborator on this code base?

**Comment by YJack0000** [comment]
Oh, the automation part is not something I plan to work on immediately; I might tackle it during the summer vacation, haha! 
Right now, my priority is to refine and finish the core functionalities of the project.

**Comment by yungyuc** [comment]
That is nice.  I think prioritizing for the completion of the project is a good idea.  Presentation should take even higher precedence, IMO.
